name: 'Update by stargazed'
# This workflow runs at 00:30 everyday
on:
  schedule:
    -
      cron: '10 6 * * *'
permissions: write-all
jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Use GitHub Actions'
        uses: actions/checkout@v2
      -
        name: 'Use Node.js 19.x'
        uses: actions/setup-node@v1
        with:
          node-version: 19.x
      -
        name: 'Clone stargazed'
        run: 'git clone https://github.com/hugefiver/stargazed.git stargazed'
      - 
        name: 'Install dependencies'
        working-directory: './stargazed'
        run: 'corepack prepare yarn@3.4.1 --activate && yarn install'
      -
        name: 'Update Repo'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        working-directory: './stargazed'
        run: 'yarn stargazed --username "hugefiver" --token ${GITHUB_TOKEN} --repo "mystars" --message "stargazed update by GitHub Actions Workflow" --sort'
